name: Docker Build and Push to Azure Container Registry

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

env:
  AZURE_REGISTRY_NAME: ksacr0808.azurecr.io
  PUBLIC_API_IMAGE_NAME: eshoppublicapi
  WEB_IMAGE_NAME: eshopwebmvc

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build PublicApi Docker image
      run: |
        cd src/PublicApi
        docker build -t ${{ env.PUBLIC_API_IMAGE_NAME }}:latest .

    - name: Build Web Docker image
      run: |
        cd src/Web
        docker build -t ${{ env.WEB_IMAGE_NAME }}:latest .

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_REGISTRY_NAME }}
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}  # Set this in your GitHub secrets
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}  # Set this in your GitHub secrets

    - name: Push PublicApi to Azure Container Registry
      run: |
        docker tag ${{ env.PUBLIC_API_IMAGE_NAME }}:latest ${{ env.AZURE_REGISTRY_NAME }}/${{ env.PUBLIC_API_IMAGE_NAME }}:latest
        docker push ${{ env.AZURE_REGISTRY_NAME }}/${{ env.PUBLIC_API_IMAGE_NAME }}:latest

    - name: Push Web to Azure Container Registry
      run: |
        docker tag ${{ env.WEB_IMAGE_NAME }}:latest ${{ env.AZURE_REGISTRY_NAME }}/${{ env.WEB_IMAGE_NAME }}:latest
        docker push ${{ env.AZURE_REGISTRY_NAME }}/${{ env.WEB_IMAGE_NAME }}:latest