name: Docker Build and Push to Azure Container Registry(OIDC)

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

env:
  AZURE_REGISTRY_NAME: ksacr0808.azurecr.io
  PUBLIC_API_IMAGE_NAME: eshoppublicapi
  WEB_IMAGE_NAME: eshopwebmvc

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Az CLI login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Docker login
      run: az acr login --name ksacr0808

    - name: Build and push Docker image
      run: |
        docker-compose build
        docker-compose push

    - name: Logout from Azure CLI
      run: az logout